version: "3"

services:
  test-react-app:
    image: test-react-app
    build:
      ./frontend/
    stdin_open: true
    ports:
    - "3000:3000"
    networks:
      - mern-app

  test-api-server:
    image: test-api-server
    build:
      ./backend/
    ports:
      - "5000:5000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
